theme: minima
title: Iain
description: Useful and/or interesting things I've learned
author: ilmcconnell
minima:
  nav_pages:
    - about.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/ilmcconnell"
    - title: ORCID
      icon: orcid
      url: "https://orcid.org/0000-0002-9982-7088"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/iain-mcconnell/"
