theme: minima
title: Iain
description: Useful and/or interesting things I've learned
author: ilmcconnell
minima:
  nav_pages:
    - about.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/ilmcconnell"
  
